@startuml

class Director {
	builder
	construct()
}

abstract class Builder {
	{abstract} buildPart1()
	{abstract} buildPart2()
	{abstract} buildPart3()
}

class ConcreteBuilder {
	buildPart1()
	buildPart2()
	buildPart3()
	getResult()
}

class Product {
}

Builder <--o Director
Builder <|-- ConcreteBuilder
Product <-- ConcreteBuilder : Creates <

@enduml