@startuml
skinparam classAttributeIconSize 0

class SomeClass {
	- privateField
	# protectedField
	+ publicField
	~ packageField

	- privateMethod()
	# protectedMethod()
	+ publicMethod()
	~ packageMethod()
}
@enduml