@startuml
[-> People : usePhone
activate People

People -> Phone : useCamera
activate Phone

Phone -> Camera : doPicture
activate Camera
Camera --> Phone
deactivate Camera

Phone --> People
deactivate Phone

People --> Phone : savePicture
activate Phone

Phone --> People
deactivate Phone

[<- People
deactivate People
@enduml