@startuml

abstract class Component {
	{abstract} method1()
	{abstract} method2()
	{abstract} method3()
}

class ConcreteComponent {
	method1()
	method2()
	method3()
}

abstract class Decorator {
	component
}

class ConcreteDecorator {
	method1()
	method2()
	method3()
}

Component <|-- ConcreteComponent
Component <|-- Decorator
Component <--o Decorator
Decorator <|-- ConcreteDecorator

@enduml