@startuml

abstract class Entry {
	int num
	Entry (int num)
	{abstract} int getCount()
	{abstract} int getSum()
	Entry add(Entry entry)
}

class Leaf {
	Leaf(int num)
	int getCount()
	int getSum()
}

class Node {
	List<Entry> children
	Node(int num)
	int getCount()
	int getSum()
	Entry add(Entry node)
}

Entry <|-- Leaf
Entry <|-- Node
Entry <--o Node

@enduml