@startuml
skinparam linetype ortho

package "Runtime Data Area" <<Node>> {
	package "Method Area" <<Rectangle>> {
	}
	package "Heap" <<Rectangle>> {
	}
	package "JVM Language Stacks" <<Rectangle>> {
		package "Thread_1" <<Rectangle>> {
			rectangle "Stack Frame_1" as sk1{
						rectangle "Local Variable Array_1" as lva1{
            			}
            			rectangle "Operand stack_1" as os1{
            			}
            			rectangle "Frame data_1" as fa1{
            			}

						lva1 -[hidden]- os1
						os1 -[hidden]- fa1
			}
		}
		package "Thread_2" <<Rectangle>> {
			rectangle "Stack Frame_2" as sk2{
						rectangle "Local Variable Array_2" as lva2{
            			}
            			rectangle "Operand stack_2" as os2{
            			}
            			rectangle "Frame data_2" as fa2{
            			}

						lva2 -[hidden]- os2
						os2 -[hidden]- fa2
			}
		}

'		"Thread_1" .[hidden].> "Thread_2"
	}
	package "PC Registers" <<Rectangle>> {
		package "PC Register for Thread_1" <<Rectangle>> {
		}
		package "PC Register for Thread_2" <<Rectangle>> {
		}
		package "PC Register for Thread_n" <<Rectangle>> {
		}

		"PC Register for Thread_1" -[hidden]-> "PC Register for Thread_2"
		"PC Register for Thread_2" -[hidden]-> "PC Register for Thread_n"
	}
	package "Native Method Stack" <<Rectangle>> {
	}

	"Method Area" -[hidden]-> "Heap"
	"Heap" -[hidden]-> "Native Method Stack"
}


@enduml