@startuml

interface "Task" as t

queue "\ninbound queue\n" as iq

t -r-> iq :submit

rectangle "Thread 1" as th1

queue "deque" as d1

rectangle "Thread 2" as th2

queue "deque(empty)" as d2

th1 -u-> iq :take
th2 -u-> iq :take

th1 --> d1 :push
th1 <-- d1 :pop
th2 --> d2 :push
th2 <-- d2 :pop

th2 --> d1: steal









@enduml