@startuml

title int result = methodNum * 2;

rectangle "Stack" {
	rectangle "methodA" {
		rectangle "result = 22" as result
		rectangle "methodNum = 11" as methodNum
		rectangle "param = 10" as param

		result -[hidden]down- methodNum
		methodNum -[hidden]down- param
	}
	rectangle "main" {
		rectangle "mainNum = 10" as mainNum
	}

	methodA -[hidden]d-main
	param -[hidden]d- mainNum
}


@enduml