@startuml
skinparam linetype ortho

title methodA(exam);

rectangle "Stack" {
	rectangle "methodA" {
		rectangle "param"
	}
	rectangle "main" {
		rectangle "exam2"
		rectangle "exam"

		exam2 -[hidden]d- exam
	}

	methodA -[hidden]d- main
}

cloud "Heap" {
	rectangle "Exam:1000" as Exam1000 {
		rectangle "num = 1" as num1000
		rectangle "str = "str1"" as str1000
		num1000 -[hidden]d- str1000
	}
}

Stack -[hidden]r-Heap

exam -up-> Exam1000
exam2 --> Exam1000
param --> Exam1000

@enduml