@startuml
'skinparam nodesep 10
'skinparam ranksep 20
'skinparam linetype ortho

title
	Object's life-cycle
endtitle

:Created;
:Initialized;
:StronglyReachable;
split
	:SoftlyReachable;
	:WeaklyReachable;
split again
	:SoftlyReachable;
split again
	:WeaklyReachable;
split again
end split
:Finalized;
:PhantomReachable;

@enduml