@startuml
skinparam linetype ortho

title String b = "hello";

rectangle "Stack" {
	rectangle "main" {
		rectangle "b"
		rectangle "a"

		b -[hidden]d- a
	}
}

cloud "Heap" {
	rectangle "String Pool" {
		rectangle "hello"
	}
}

Stack -[hidden]r-Heap
a -r-> hello
b -u-> hello

@enduml