@startuml
'skinparam linetype polyline
'skinparam linetype ortho

rectangle "pub" as pub {

}

rectangle "reduceConcatProcessor" as reduceConcatProcessor {
	rectangle "BiFunction" as func
}

rectangle "sub" as sub {

}

pub -> func :1...5
func -> sub :'12345'





@enduml