@startuml

[Source Code(.java)] -> [Compiler(javac)]
[Compiler(javac)] -> [Byte code(.class)]
[Byte code(.class)] --> JVM1
[Byte code(.class)] --> JVM2
[Byte code(.class)] --> JVM3
JVM1 --> [Interpreter for Mac]
JVM2 --> [Interpreter for Windows]
JVM3 --> [Interpreter for Linux]

@enduml