@startuml
skinparam linetype ortho

title list.add(new Exam(2, "str2"));

rectangle "Stack" {
	rectangle "main" {
		rectangle "exam"
		rectangle "list"
	}

	exam -[hidden]u-list
}

cloud "Heap" {
	rectangle "Exam:1000" as Exam1000 {
		rectangle "num = 1" as num1000
		rectangle "str = "str1"" as str1000
		num1000 -[hidden]d- str1000
	}

	rectangle "List:1001" as List1001

	rectangle "Exam:1002" as Exam1002 {
		rectangle "num = 2" as num1002
		rectangle "str = "str2"" as str1002
		num1002 -[hidden]d- str1002
	}

	Exam1000 -[hidden]u- List1001
	List1001 -d-> Exam1002
}

Stack -[hidden]r-Heap

exam -r-> Exam1000
list -r-> List1001

@enduml