@startuml

package "Stack" <<Node>> {
	package "reference1" <<Rectangle>> {
	}
	package "reference2" <<Rectangle>> {
	}
	package "list" <<Rectangle>> {
	}
	package "num" <<Rectangle>> {
	}

	"reference1" -[hidden]- "reference2"
	"reference2" -[hidden]- "list"
	"list" -[hidden]- "num"
}

package "Heap" <<Node>> {
	package "Object1" <<Rectangle>> {
	}
	package "Object2" <<Rectangle>> {
	}
	package "Object3" <<Rectangle>> {
	}

	package "String1" <<Rectangle>> {
	}
	package "String2" <<Rectangle>> {
	}
	package "List" <<Rectangle>> {
	}

	"List" -[hidden]- "String1"
	"Object1" -[hidden]- "Object2"
}

"reference1" --> "String1"
"reference2" --> "String2"
"list" --> "List"

@enduml