@startuml
skinparam linetype ortho

title param = new Exam(2, "str2");

rectangle "Stack" {
	rectangle "methodA" {
		rectangle "param"
	}
	rectangle "main" {
		rectangle "exam"
	}

	methodA -[hidden]d- main
}

cloud "Heap" {
	rectangle "Exam:1000" as Exam1000 {
		rectangle "num = 1" as num1000
		rectangle "str = "str1"" as str1000
		num1000 -[hidden]d- str1000
	}
	rectangle "Exam:1001" as Exam1001 {
		rectangle "num = 2" as num1001
		rectangle "str = "str2"" as str1001
		num1001 -[hidden]d- str1001
	}

	Exam1000 -[hidden]u- Exam1001
}

Stack -[hidden]right-Heap

exam -right-> Exam1000
param -right-> Exam1001

@enduml