@startuml
skinparam linetype ortho

title str += " world!!;

rectangle "Stack" {
	rectangle "methodA" {
		rectangle "str"
	}

	rectangle "main" {
		rectangle "a"
	}

	methodA -[hidden]d- main
}

cloud "Heap" {
	rectangle "String Pool" {
		rectangle "hello"
		rectangle "hello world!!" as helloworld
	}
}

Stack -[hidden]r-Heap
a -r-> hello
str -u-> helloworld

@enduml