@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
hide methods
hide stereotypes

entity (Member) {
  primary_key(id)
  team
  name
}

entity (Team) {
  primary_key(id)
  name
}

Member --> Team
@enduml