@startuml

!include <tupadr3/common>
!include <tupadr3/font-awesome/server>
!include <tupadr3/font-awesome/database>
!include <tupadr3/font-awesome-5/docker>
!include <tupadr3/govicons/user>


FA5_DOCKER(dev_docker, 개발환경, rectangle, DodgerBlue) #White
FA5_DOCKER(repo_docker, 컨테이너 이미지 저장소, rectangle, DodgerBlue) #White
FA5_DOCKER(server_docker1, 서버1, rectangle, DodgerBlue) #White
FA5_DOCKER(server_docker2, 서버2, rectangle, DodgerBlue) #White
FA5_DOCKER(server_docker3, 서버3, rectangle, DodgerBlue) #White

rectangle "Load Balancer" as lb #White

GOV_USER(user, 사용자) #White

dev_docker -right-> repo_docker : 이미지 업로드
repo_docker -down-> server_docker1
repo_docker -down-> server_docker2 : 배포
repo_docker -down-> server_docker3

lb -up-> server_docker1
lb -up-> server_docker2
lb -up-> server_docker3

user -left-> lb

@enduml