@startuml

rectangle "Kubernetes Cluster" {
	rectangle "Pod" as p {

	}

	rectangle "Service(service-externalname)" as s {

	}
}

rectangle "google.com" as g {

}

p -r-> g : 3. 접속
p --> s : 1. DNS 요청
s --> p : 2. CNAME 값(googlec.om) 반환


@enduml