@startuml

class WeightEntry{
	key
	weight
}

abstract class WeightSelector {
	totalWeight
	random
	WeightSelector()
	addEntry(entry)
	getRandomWeight
	checkProcess(needCount, isDuplicated)
	processSelectKey(needCount, isDuplicated)
	{abstract} add(entry)
	{abstract} getEntrySize()
	{abstract} getSelectKeyList(needCount, isDuplicated)
}

class ProtoWeightSelector {
	entryMap
	ProtoWeightSelector()
	remoteEntry(entry)
	add(entry)
	getEntrySize()
	getSelectedKeyList(needCount, isDuplicated)
}

WeightSelector <|-- ProtoWeightSelector
WeightEntry <--o WeightSelector

@enduml