@startuml

rectangle "Host" as host {
	rectangle "eth0" as host_eth0 {
		card "eth0-macvlan" as eth0_macvlan

		rectangle "eth0.10" {
			card "eth0.10-macvlan" as eth0_10_macvlan
		}
	}


	rectangle "Container 1" as container_1 {
		rectangle "eth0" as docker_eth0_1 {
			card "123.11.11.2" as 111
		}
	}


	rectangle "Container 2" as container_2 {
		rectangle "eth0" as docker_eth0_2 {
			card "123.11.11.3" as 222
		}
	}

	eth0_macvlan -d- docker_eth0_1
	eth0_10_macvlan -d- docker_eth0_2


'	host_eth0 -[hidden]d- host_docker0
'	host_docker0 -[hidden]d- host_veth_1
'	host_docker0 -[hidden]d- host_veth_2
'	host_veth_1 -[hidden]d- container_1
'	host_veth_2 -[hidden]d- container_2
}

@enduml