@startuml

participant kafkainboundtopic as "Kafka Inbound Topic"
participant kafkainboundoffset as "Kafka Inbound Offset"
participant kafkaoutbound as "Kafka Outbound"
participant consumer as "Consumer"
participant 3service as "3rd party Service"
participant db as "DB"

title Kafka Transaction

group no failure
    kafkainboundtopic -> consumer : consume
    activate consumer
    consumer -> 3service : POST
    consumer -> db : INSERT record
    note over consumer : Begin Kafka Transaction
    consumer -> kafkaoutbound : produce
    consumer -> kafkainboundoffset : write
    note over consumer : Commit Kafka transaction
    consumer -[hidden]-> db
    deactivate
end

group failure after POST & INSERT
    kafkainboundtopic -> consumer : consume
    activate consumer
    consumer -> 3service : POST
    consumer -> db : INSERT record
    consumer -[hidden]-> db
    destroy consumer
    deactivate consumer

    kafkainboundtopic -> consumer : consume
    activate consumer
    note over consumer : Duplicate POST
    consumer -> 3service : POST
    note over consumer : Duplicate INSERT
    consumer -> db : INSERT record
    note over consumer : Begin Kafka Transaction
    consumer -> kafkaoutbound : produce
    consumer -> kafkainboundoffset : write
    note over consumer : Commit Kafka transaction
    consumer -[hidden]-> db
    deactivate
end

group failure after Produce
    kafkainboundtopic -> consumer : consume
    activate consumer
    consumer -> 3service : POST
    consumer -> db : INSERT record
    note over consumer : Begin Kafka Transaction
    consumer -> kafkaoutbound : produce
    consumer -[hidden]-> db
    destroy consumer
    note over kafkaoutbound : Kafka transaction rollback
    deactivate consumer

    kafkainboundtopic -> consumer : consume
    activate consumer
    note over consumer : Duplicate POST
    consumer -> 3service : POST
    note over consumer : Duplicate INSERT
    consumer -> db : INSERT record
    note over consumer : Begin Kafka Transaction
    consumer -> kafkaoutbound : produce
    consumer -> kafkainboundoffset : write
    note over consumer : Commit Kafka transaction
    consumer -[hidden]-> db
    deactivate
end


group consume time out
    kafkainboundtopic -> consumer : consume
    activate consumer
    consumer -> 3service : POST
    consumer -> db : INSERT record
    note over consumer : long time process
    note over consumer : consume time out(kafka rebalancing)
    note over consumer : Begin Kafka Transaction
    consumer -> kafkaoutbound : produce
    consumer -> kafkainboundoffset : write
    note over consumer : Commit Kafka transaction
    consumer -[hidden]-> db
    deactivate

    group new consumer
        note over consumer : kafka assign other consumer

        kafkainboundtopic -> consumer : consume
        activate consumer
        note over consumer : Duplicate POST
        consumer -> 3service : POST
        note over consumer : Duplicate INSERT
        consumer -> db : INSERT record
        note over consumer : Begin Kafka Transaction
        consumer -> kafkaoutbound : produce
        consumer -> kafkainboundoffset : write
        note over consumer : Commit Kafka transaction
        consumer -[hidden]-> db
        deactivate
    end
end

@enduml